Fixes of i18n on readme.md
vtex-apps/store-form pull request #77
Opened 2023-06-29 11:05 UTC by GeorgeLimaDev

#### What problem is this solving?

It relates to task [LOC-10897](https://vtex-dev.atlassian.net/browse/LOC-10897) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).

2023-07-03 12:54 UTC, julia-rabello requested changes

2023-07-03 12:54 UTC, julia-rabello commented on docs/README.md
```suggestion
| `formSubmitButton` |
| `formErrorServer` |
| `formErrorUserInput` |
```

2023-07-04 22:05 UTC, julia-rabello requested changes

2023-07-04 22:05 UTC, julia-rabello commented on docs/README.md
> +  }
```suggestion
    ```json
    "dependencies": {
        "vtex.store-form": "0.x"
    }
    ```
```

2023-07-04 22:05 UTC, julia-rabello commented on docs/README.md
> +}
Substituir as linhas 40 até 53 por:

```
    ```json
    {
        "store.product": {
            "children": [
                "flex-layout.row#product-breadcrumb",
                "flex-layout.row#product-main"
                "flex-layout.row#form",
                "shelf.relatedProducts",
                "product-reviews",
                "product-questions-and-answers"
            ]
        },
        ...
    }
    ```
```

2023-07-05 13:09 UTC, julia-rabello approved these changes

2023-07-14 11:12 UTC, GeorgeLimaDev commented
@vtex-apps/store-framework-devs I need a hand with a code owner review. It was requested on the #store-framework Slack channel previously: [Slack message](https://vtex.slack.com/archives/C01PRGM0WG1/p1688564819437709)

2023-07-24 14:32 UTC, merged